# Generated by Django 4.2.5 on 2023-10-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='company/images/')),
                ('description', models.TextField()),
                ('employee_count', models.IntegerField()),
                ('Linkedin', models.URLField()),
                ('website', models.URLField()),
                ('facebook', models.URLField()),
                ('twitter', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
    ]
